FROM postgres:15

RUN apt-get update && apt-get install -y build-essential clang postgresql-server-dev-15 git \
    && git clone --depth 1 https://github.com/pgvector/pgvector.git \
    && cd pgvector && make && make install \
    && apt-get remove -y build-essential clang git \
    && apt-get autoremove -y \
    && rm -rf /var/lib/apt/lists/*
